---
site: bookdown::bookdown_site
title: 'Exploration of Multi-Response Multivariate Methods'
alt-title: 'Utforskning av multi-respons multivariate metoder'
date: "`r format(Sys.Date(), format = '%m, %Y')`"
year: "`r format(Sys.Date(), format = '%Y')`"
month: "`r format(Sys.Date(), format = '%b')`"
location: 'Ås'
docsite: 'https://therimalaya.github.com/thesis'
author:
  name: "Raju Rimal"
  email: 'raju.rimal@nmbu.no'
  homepage: 'https://www.mathatistics.com/'
  affiliation: |
    Biostatistics\
    Dept. of Chemistry, Biotechnology and Food Science\
    Norwegian University of Life Sciences
supervisors:
  - title: 'Professor'
    name: 'Solve Sæbø'
    affiliation: |
      Prorector\
      Norwegian University of Life Sciences\
      Ås, Norway
  - title: 'Associate Professor'
    name: 'Trygve Almøy'
    affiliation: |
      Dept. of Chemistry, Biotechnology and Food Science\
      Norwegian University of Life Sciences\
      Ås, Norway
bibliography: 'References'
biblio-style: 'plainnat'
biblio-title: 'References'
natbiboptions: 'authoryear'
nociteall: true
toc: true
lof: true
lot: true
knit: 'bookdown::render_book'
logo: "Logo.pdf"
logo-width: '0.6\linewidth'
thesis-number: "1234:56"
issn: "1234-5678"
isbn: "123-45-678-1234-5"
quote: "The goal is to turn data into information, and information into insight."
quote-author: "- Carly Fiorina, former CEO of Hewlett-Packard"
keywords: ['model-comparison ', 'multi-response ', 'simrel ']
acknowledgments: chapters/00-Acknowledgment.md
summary: chapters/00-Summary.md
sammendrag: chapters/00-Sammendrag.md
preface: chapters/00-Preface.md
papers:
  - title: "A tool for simulating multi-response linear model data"
    path: "papers/001.pdf"
  - title: "Model and estimators for partial least squares regression"
    path: "papers/002.pdf"
  - title: "Comparison of Multi-response Prediction Methods"
    path: "papers/003.pdf"
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  comment    = NA,
  out.width  = '100%',
  dev        = c('pdf', 'svg'),
  fig.retina = 2,
  fig.pos    = "!htb",
  echo       = FALSE
)
```

# Introduction #

As a consequence of the development in the technology and computing power, data science discipline has emerged from the explosion of data. Extracting information from this chaotic heap of data has become another problem. Many statistical and machine learning tools are being devised for this purpose. However the difference in the approach, these methods target the problem, makes them distinct and useful to deal with certain aspect of the data. Most of these problems lie in identifying the relationship between variables. This thesis confined itself in the exploration of linear relationship where a set of independent variables called predictor variables affect another set of dependent variables called response variables. Normally only subspace of predictor variables are relevant for a subspace of response variables to define its linear relationship. This brings to the concept of relevant and irrelevant space. Methods like Principal Components Regression (PCR), Partial Least Squares (PLS) and many other variants of PLS has leveraged this concept and are serving  as a prime tool in many discipline, most notably chemometrics. A relatively new methods called envelopes has used this concept of dimension reduction such that only the relevant (material) part in both response and predictors can be used to estimate the underlying linear model. Although the underlying population model is similar in these methods, they estimate the model parameter differently. Evaluation of these methods is crucial in order to understand their pros and cons on dataset with certain properties. This thesis will explore some of these methods and access their estimative and predictive strength and weaknesses through both simulated and real datasets. This exploration adds a reference for researchers and motivates them for using different methods based on the properties of the data they are working on.

This study is exploratory in nature where we assess and compare different multi-response multivariate methods but most importantly study their interaction with the properties of the data. The properties include the correlation between predictor variables, the position of principal components of predictor variables (predictor components) that are relevant for certain principal components of response variables (response components), the amount of correlation between the response variables and the number of predictor variables. The effect of correlation structure of response matrix is less explored and it is expected to add some light on how similar and how different the methods are in terms of modelling this structure. In order to simulate data with these properties varying at different levels, we have created an R-package called `simrel` which is an extension of the previous version of it introduced by @saebo2015simrel to incorporate multiple response.

## Background ##

In the following few subsection, I will discuss few related topics in this thesis. These topics are extensively used in all the papers which are summarized in next chapter.

### Multivariate Linear Regression Model ###
A model that linearly relates a random variable $\mathbold{y}$ consists of $m$ response variables with another random variable $\mathbold{x}$ consists of $p$ predictor variables through regression coefficient $\boldsymbol{\beta}$ is often written as,

\begin{equation}
\mathbold{y} = \boldsymbol{\mu}_y + \boldsymbol{\beta}^t\left(\mathbold{x} - \boldsymbol{\mu}_x\right) + \boldsymbol{\varepsilon}
\end{equation}
where $\boldsymbol{\varepsilon} \sim \textsf{N}\left(\mathbold{0}, \boldsymbol{\Sigma}_{y|x}\right)$, $\boldsymbol{\mu}_y$ is the mean vector of $\mathbold{y}$ and $\boldsymbol{\mu}_x$ is the mean vector of $\mathbold{x}$.

Here the regression coefficient $\boldsymbol{\beta} = \boldsymbol{\Sigma}_{xx}^{-1}\boldsymbol{\Sigma}_{xy}$ 
- A linear model 
- Linear relationship model

### Relevant Space and Relevant Components ###
- Connection to relevant space
- How relevant space is connected to relevant component and dimension reduction
- Concept linked to simrel and various methods

### Estimation and Prediction ###
- What is the difference between estimation and prediction
- How large estimation error can also result in close prediction
- What have we used in these papers for comparison

### Multivariate Analysis of Variance ###
- What is ANOVA in multi-response setting
- Why is it different from regular ANOVA
- How we have used this method in our study
- What statistic we have used for comparison

## Previous Studies ##
- Previous similar studies
- Mostly used the methods developers
- Connection with data properties in an experimental manner is not explored properly and comprehensively
- Effect on multi-response model and the effect of correlation structure on the methods is not studied for these methods to our knowledge

## Simulation and Experimental Design ##

- Different papers have different design
- Last two papers have similar design as the fourth paper extends the third
- Following factors and their interaction is studied,
    - Low and High multicollinearity
    - Position of predictor components that are relevant for specific response components
    - Number of predictor variables
    - Low to High correlation between response variables

The exploration and findings of the papers are discussed in brief in next chapter.

