# Discussions, Conclusions and Future Perspectives

## Discussions and Conclusions
- Get the conclusion of all the papers
- Add a paragraph to say something on big picture

# Previous Studies #
- Previous similar studies
- Mostly used the methods developers
- Connection with data properties in an experimental manner is not explored properly and comprehensively
- Effect on multi-response model and the effect of correlation structure on the methods is not studied for these methods to our knowledge
- Envelope model is not accessed in these applied setting and data related to chemometrics
The exploration and findings of the papers are discussed in brief in next chapter.

## Limitations and Future Perspectives
- Ridge, Lasso and other methods could have been used for comparison but since they are not based on the relevant components. Although we did some basic comparison by including them but they require a separate and comprehensive study.
- Highly applied form of comparison but it can be extended also to the comparison of their mathematical formulation. This has been done in second paper for a single response case but the simultaneous envelope and multi-response case needs a separate study.
- In the current state, the simulation tool assumes that the predictor components relevant for one response components is not relevant for another. This can be further studied and can be extended to simulate more general data structure.
- The simulation tool can also be extended to simulate ANOVA model and model with multi-class categorical response model. This increases the applicability of tools in more research areas and educational purpose.






