# Limitations \& Future Perspectives

Although the studies in the thesis are all comparisons of methods, it is important to make those comparisons not only to evaluate the methods but also to understand their interaction with various properties that can exist in real data. This provides an example assessment for method developers and gives a clear understanding of the methods under comparisons for these specific cases to other researchers.

The study mostly covers the comparisons through simulated data and some real data, but it also provides a direction for further exploration of these methods and other methods as well. Ridge, Lasso and other methods could have been used for comparison, but since they are not explicitly based on the concept of relevant components we have discarded them from these comparisons at this point. However we did some basic comparison by including them, but they require a separate and a more comprehensive study.

The study is highly based on simulated data and somewhat on real data, it could also have been extended to the comparison of their mathematical formulation. This has been done, to some extent, in the second paper for a single response case but the simultaneous envelope and multi-response case needs a separate study.

In the current state, the simulation tool assumes that the predictor components relevant for one response component are not relevant for others. This can be further studied and can be extended to simulate a more general data structure. Additionally, due to the rise in the popularity of machine learning methods, a similar comparative study of statistical and machine learning methods is also recommended as a future perspective of this study.
